apiVersion: 1

deleteDatasources:
  - name: InfluxDB

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: speedtest
    user: admin
    password: password
    url: http://influxdb:8086
